Repository lemma-osu/sklearn-raster, pull requests merged in 2025-03, with the labels that each got.

#41 Implement NoData skipping and other `apply` params
  src/sklearn_raster/estimator.py
  src/sklearn_raster/image.py
  src/sklearn_raster/types.py
  src/sklearn_raster/ufunc.py
  src/sklearn_raster/utils/wrapper.py
  tests/image_utils.py
  tests/test_image.py
Labels: enhancement

#46 Create new hatch shell for `sklearn-raster[tutorials]`
  pyproject.toml
Labels: dx

#45 Refactor flattening
  src/sklearn_raster/image.py
  src/sklearn_raster/ufunc.py
  src/sklearn_raster/utils/image.py
Labels: enhancement

#49 Fix bug with ufuncs that squeeze the feature dimension
  src/sklearn_raster/ufunc.py
  tests/test_image.py
Labels: bug

#50 Support wrapped methods with n-dimensional data
  src/sklearn_raster/estimator.py
  src/sklearn_raster/image.py
  src/sklearn_raster/utils/image.py
  tests/image_utils.py
  tests/test_estimator.py
Labels: enhancement

#52 Update precommit hooks to latest
  .pre-commit-config.yaml
  tests/conftest.py
Labels: dx
